spring:
  application:
    name: users-service
  datasource:
    url: jdbc:postgresql://users-service-db:5432/users-service-db
    username: postgres
    password: postgres
  eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8070/eureka/

