spring:
  application:
    name: authentication-service
  datasource:
    url: jdbc:postgresql://authentication-service-db:5432/authentication-service-db
    username: postgres
    password: postgres

        


